baseurl = "http://alebaffa.github.io/blog"
languageCode = "en-us"
title = "alebaffa's"
theme = "beautifulhugo"
disqusShortname = "alessandrobaffa"
pygmentsuseclasses = true

[Params]
  logo = "img/speaker.jpg"

[Author]
  name = "Alessandro Baffa"
  email = "alessandro.baffa@gmail.com"
  github = "alebaffa"
  twitter = "alebaffa"
  linkedin = "pub/alessandrobaffa"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
